version: '3'
services:
  postgres:
    image: postgres:10.1
    volumes:
    - postgres-volume:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=ztadmin
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=metabase

  metabase:
    image: metabase/metabase:latest
    volumes:
    - metabase-volume:/metabase-data 
    ports:
    - 3000:3000
    links:
    - postgres
    depends_on:
    - postgres
    environment:
    - JAVA_TIMEZONE=America/Mexico_City
    - MB_DB_TYPE=postgres
    - MB_DB_DBNAME=metabase
    - MB_DB_PORT=5432
    - MB_DB_USER=ztadmin
    - MB_DB_PASS=secret
    - MB_DB_HOST=postgres

volumes:
    postgres-volume:
    metabase-volume:
